version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_0705_AWSSTAGEProject
  gitServerName: SIQA_KVV_IBM
  gitUrl: https://github.com/Karthik-V-IBM-10
  gitUsername: Karthik-V-IBM-10
  gitBranch: main
- name: SSL_JDBC_Test
  gitServerName: SIQA_KVV_IBM
  gitUrl: https://github.com/prabhakarsag
  gitUsername: Karthik-V-IBM-10
  gitBranch: main
- name: JMS2waySSL
  gitServerName: SIQA_KVV_IBM
  gitUrl: https://github.com/prabhakarsag
  gitUsername: Karthik-V-IBM-10
  gitBranch: main
- name: JMSTest
  gitServerName: SIQA_KVV_IBM
  gitUrl: https://github.com/prabhakarsag
  gitUsername: Karthik-V-IBM-10
  gitBranch: main
